### ISSUE TITLE
Creating a list of Items when Entered

### ISSUE THREAD

**Issue by krazykaushal** [MSTC-DA-IICT/Movie-WatchList#1]
Right now what the site is doing is that Whenever I press Enter after writing the movie name it resets the input and the movie name entered is not visible.

So create a Javascript file such that it stores the list of movie names and shows it as a list. 

**Tasks to be completed:**

1. Create a list of the movies that are Entered in the given field.
2. Show the list entered in an attractive-looking way.

**Comment by Abhirambvss** [comment]
I will work on this issue

**Comment by krazykaushal** [comment]
Issue assigned to @Abhirambvss 
Thanks

**Comment by krazykaushal** [comment]
@Abhirambvss React to this message if you are working on this issue or not. And if you do not I have to assign this to someone else.
Thanks.

**Comment by Abhirambvss** [comment]
I am working on it. Need some more time. I will definitely complete it by this weekend.

**Comment by Abhirambvss** [comment]
You unassigned me, so I thought you had assigned it to someone. That's why I did not do the work

**Comment by Akhil2193** [comment]
Hey @krazykaushal I would like to work on this issue. Can you assign this to me ?

**Comment by krazykaushal** [comment]
Issue assigned to @Akhil2193. And reply if you are ready to work on this issue.
Thanks

**Comment by Akhil2193** [comment]
Yeah, I am working on it
