### ISSUE TITLE
Add a feature to mark the movie as watched

### ISSUE THREAD

**Issue by krazykaushal** [MSTC-DA-IICT/Movie-WatchList#2]
After we have created the list, suppose we have watched one of the movies from the list, then we want a feature to mark that movie as watched.

**Tasks to be completed from this**:

-  Add a mark as watched feature either by button or certain event like left click

**Comment by Abhirambvss** [comment]
I will work on this issue too.

**Comment by krazykaushal** [comment]
Issue assigned to @Abhirambvss 
Thanks.

**Comment by krazykaushal** [comment]
This issue is now available for everyone.
